### ISSUE TITLE
Photos 'uploading' but not being shown

### ISSUE THREAD

**Issue by ghost** [sebt3/hubzilla#1]
Hi Seb,

Good to talk to you on the hub. 

https://i.imgur.com/VrMJexk.png

As you can see, the files are uploading, (I tried 17 times, different sizes & formats). I think it might have something to do with a Hubzilla setting? I looked from the php angle, and I havent changed anything PHP since I got the hub up and running.

I did create some service classes, though, so I'm going to fiddle with that a bit. Service classes shouldn't be producing that type of behaviour, all my service classes have very generous limits.

FYI: Photos can be uploaded in photos plugin, and while using 'profile photo' upload, but!
Nothing is visible; in the profile photo selection, nor in the photo plugin

**Comment by sebt3** [comment]
Ok, I'm back home, sorry for the wait. This issue should have been fixed with my second upload to dockerhub (I did upload a few version since) : I got it initially.
The root of this issue is : I forgot to add the `imagemagik` package to the image.But it's done since a while.
Since I cant reproduce on my own hub (even batch upload works), would you please help me check find where your issue lie.
0) Get container ID and use it to run command from within :
`docker stack ps hubzilla -f name=hubzilla_hubzilla.1 --no-trunc|awk -v N=hubzilla_hubzilla.1 '$2==N{print N"."$1}'`
and then `docker exec -it <id from previous command> sh -l`
1) from within the container, run `convert -version`
2) from within the container, run `util/config system ignore_imagick`
And give me the result from 1 and 2

**Comment by ghost** [comment]
Hi Seb,

Just completed updating the image, and it's still happening. Since updating, the service classes i made, have disappeared; so they definitely weren't the reason. Here's the info you requested:

1.
Version: ImageMagick 7.0.8-68 Q16 x86_64 2019-12-18 https://imagemagick.org
Copyright: © 1999-2019 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules 
Delegates (built-in): bzlib cairo fontconfig freetype gslib heic jng jpeg lcms ltdl pangocairo png ps rsvg tiff webp x xml zlib

2.
config[system][ignore_imagick] = true

**Comment by sebt3** [comment]
Ooookaaayyyy, so you have the same image I'm running (which mean same php.ini configuration and same hubzilla code). You seems to have the same hubzilla configuration, and I dont have the issue.
New checks :
`util/config system maximagesize` (should be 0)
What's the value of `client_max_body_size` in your nginx configuration ? (should be 100m)
If you got the same value, then i'm probably clueless, and we'll need to update your forum queries.

EDIT: here is the nginx config I'm running : https://github.com/sebt3/picloud/blob/master/roles/hubzilla/templates/nginx.conf.j2

**Comment by ghost** [comment]
Hey Seb,

Thanks for the reply.
maximagesize = 0 
client_max_body_size = 100m

I'm clueless as well.

I  have today off work, I'll have a play with it.

Where do you think that we should post the issue?
Which forum?

**Comment by sebt3** [comment]
I would have gone with support, but dev works too I guess

**Comment by sebt3** [comment]
err, a few questions : 
What plateform are you using ? (amd64 I guess)
What are you using as SSL frontend ? (traefik or nginx+certbot)

**Comment by ghost** [comment]
'Fixed' by:
1. stopping container
2. removing container
3. deleting Hubzilla folder from storage
4. rebuilding docker image
5. deleting troublesome folder using the 'files' app on site


HTH
